openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a project about cloning Twitter
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags:
  - name: users
    description: Các API liên quan đến người dùng twitter
  - name: tweets
    description: Các API liên quan đến tweet
  - name: bookmarks
    description: Các API liên quan đến bookmark
  - name: likes
    description: Các API liên quan đến like
  - name: conversations
    description: Các API liên quan đến conversation
  - name: medias
    description: Các API liên quan đến media
paths:
  /users/register:
    post:
      tags:
        - users
      summary: Đăng ký
      description: Đăng ký tài khoản X
      operationId: register
      requestBody:
        description: Thông tin đăng ký
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
        required: true
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Register successfully
                  result:
                    $ref: '#/components/schemas/SuccessAuthentication'
        '422':
          description: Invalid input
  /users/login:
    post:
      tags:
        - users
      summary: Đăng nhập
      description: Đăng nhập vào hệ thống X
      operationId: login
      requestBody:
        description: Thông tin đăng nhập
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successfully
                  result:
                    $ref: '#/components/schemas/SuccessAuthentication'
        '422':
          description: Invalid input
  /users/me:
    get:
      tags:
        - users
      summary: Lấy thông tin user
      description: Lấy thông tin user
      operationId: getMe
      security:
        - BearerAuth: []
      responses:
        default:
          description: Lấy thông tin user thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/logout:
    post:
      tags:
        - users
      summary: Đăng xuất
      description: Đăng xuất khỏi hệ thống
      operationId: logout
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Đăng xuất thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successfully
        '401':
          description: Unauthorized
  /users/verify-email:
    post:
      tags:
        - users
      summary: Xác thực email
      description: Xác thực email
      operationId: verifyEmail
      security:
        - BearerAuth: []
      requestBody:
        description: Email verify token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailVerifyToken'
      responses:
        '200':
          description: Xác thực email thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Verify email successfully
                  data:
                    $ref: '#/components/schemas/SuccessAuthentication'
        '201':
          description: Email đã được xác thực(Vẫn là code 200 nhưng message khác)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already verified
        '401':
          description: Unauthorized
  /users/resend-verify-email:
    post:
      tags:
        - users
      summary: Gửi lại email xác thực
      description: Gửi lại email xác thực
      operationId: resendVerifyEmail
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Gửi lại email xác thực thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Resend verify email successfully
        '401':
          description: Unauthorized
  /users/forgot-password:
    post:
      tags:
        - users
      summary: Quên mật khẩu
      description: Quên mật khẩu
      operationId: forgotPassword
      requestBody:
        description: Email
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: meoweird@gmail.com
      responses:
        '200':
          description: Gửi email quên mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Check email to reset password
        '422':
          description: Invalid input
        '401':
          description: Unauthorized
  /users/verify-forgot-password:
    post:
      tags:
        - users
      summary: Xác thực quên mật khẩu
      description: Xác thực quên mật khẩu
      operationId: verifyForgotPassword
      requestBody:
        description: Forgot password token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordToken'
      responses:
        '200':
          description: Xác thực quên mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Verify forgot password token successfully
        '401':
          description: Unauthorized
  /users/reset-password:
    post:
      tags:
        - users
      summary: Đặt lại mật khẩu
      description: Đặt lại mật khẩu
      operationId: resetPassword
      requestBody:
        description: Mật khẩu mới
        content:
          application/json:
            schema:
              type: object
              properties:
                forgot_password_token:
                  $ref: '#/components/schemas/ForgotPasswordToken'
                password:
                  type: string
                  example: Dong2003!
                confirm_password:
                  type: string
                  example: Dong2003!
      responses:
        '200':
          description: Đặt lại mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Reset password successfully
        '422':
          description: Invalid input
        '401':
          description: Unauthorized
  /users/"me":
    patch:
      tags:
        - users
      summary: Cập nhật thông tin user
      description: Cập nhật thông tin user
      operationId: updateMe
      security:
        - BearerAuth: []
      requestBody:
        description: Thông tin cập nhật
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Le Xuan Dong
                date_of_birth:
                  type: string
                  format: ISO8601
                  example: 2023-06-08T10:17:31.096Z
                bio:
                  type: string
                  example: 'This is my bio.'
                location:
                  type: string
                  example: 'San Francisco, CA'
                website:
                  type: string
                  example: 'www.example.com'
      responses:
        '200':
          description: Cập nhật thông tin user thành công
          content:
            application/json:
              schema:
                message:
                  type: string
                  example: Update me successfully
                $ref: '#/components/schemas/User'
        '422':
          description: Invalid input
        '401':
          description: Unauthorized
  /users/change-password:
    post:
      tags:
        - users
      summary: Đổi mật khẩu
      description: Đổi mật khẩu
      operationId: changePassword
      security:
        - BearerAuth: []
      requestBody:
        description: Mật khẩu mới
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  example: Dong2003!
                new_password:
                  type: string
                  example: Dong123!
                confirm_password:
                  type: string
                  example: Dong123!
      responses:
        '200':
          description: Đổi mật khẩu thành công
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: Change password successfully
        '422':
          description: Invalid input
        '401':
          description: Unauthorized
  /users/:username:
    get:
      tags:
        - users
      summary: Lấy thông tin user theo username
      description: Lấy thông tin user theo username
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          required: true
          description: Username của user
          schema:
            type: string
      responses:
        default:
          description: Lấy thông tin user thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/refresh-token:
    post:
      tags:
        - users
      summary: Lấy lại access token
      description: Lấy lại access token
      operationId: refreshToken
      requestBody:
        description: Refresh token
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTcwMDAyMzIyNn0.bFnaBfxWl-Q48HCwAeMpNzZwTO9LEjcBd7Zyipjqr64
      responses:
        '200':
          description: Lấy lại access token thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Refresh token successfully
                  result:
                    $ref: '#/components/schemas/SuccessAuthentication'
        '401':
          description: Unauthorized
components:
  schemas:
    RegisterBody:
      type: object
      properties:
        email:
          type: string
          example: meoweird@gmail.com
        password:
          type: string
          example: Dong2003!
        confirm_password:
          type: string
          example: Dong2003!
        date_of_birth:
          type: string
          format: ISO8601
          example: 2023-06-08T10:17:31.096Z
        name:
          type: string
          example: Le Xuan Dong
    LoginBody:
      type: object
      properties:
        email:
          type: string
          example: meoweird@gmail.com
        password:
          type: string
          example: Dong2003!
    SuccessAuthentication:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MCwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTY5MTQ2OTYyNn0.HTLX20cB7_z0c9c8FDg3MIx6RJEELHHlmJNZa94ku-o
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTcwMDAyMzIyNn0.bFnaBfxWl-Q48HCwAeMpNzZwTO9LEjcBd7Zyipjqr64
    User:
      type: object
      properties:
        _id:
          type: string
          format: MongoId
          example: 64be0ad2e43d2464394feedb
        name:
          type: string
          example: Le Xuan Dong
        email:
          type: string
          example: meoweird@gmail.com
        date_of_birth:
          type: string
          format: ISO8601
          example: 2023-06-08T10:17:31.096Z
        created_at:
          type: string
          format: ISO8601
          example: 2023-03-08T12:00:00Z
        updated_at:
          type: string
          format: ISO8601
          example: 2023-03-08T12:00:00Z
        verify:
          $ref: '#/components/schemas/UserVerifyStatus'
        twitter_circle:
          type: array
          items:
            type: string
            format: MongoId
          example: ['64be0ad2e43d2464394feedb', '64be0ad2e43d2464394feedc']
        bio:
          type: string
          example: 'This is my bio.'
        location:
          type: string
          example: 'San Francisco, CA'
        website:
          type: string
          example: 'www.example.com'
        username:
          type: string
          example: 'lexuandong'
        avatar:
          type: string
          example: 'http:localhost:4000/images/avatars/lexuandong.jpg'
        cover_photo:
          type: string
          example: 'http:localhost:4000/images/avatars/lexuandong.jpg'
    UserVerifyStatus:
      type: number
      enum: [Unverified, Verified, Banned]
      example: 1
    EmailVerifyToken:
      type: object
      properties:
        email_verify_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU0MGRhYzUxNjlmYjcyZDA0NzIwNTZmIiwidG9rZW5fdHlwZSI6MywidmVyaWZ5IjowLCJpYXQiOjE2OTg3NDkxMjUsImV4cCI6MTY5ODc1MjcyNX0.SANd0C_3saBmzafLM74X6zHD0UsxG0yHrm31fnPGf3U
    ForgotPasswordToken:
      type: object
      properties:
        forgot_password_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU0MGRhYzUxNjlmYjcyZDA0NzIwNTZmIiwidG9rZW5fdHlwZSI6MywidmVyaWZ5IjowLCJpYXQiOjE2OTg3NDkxMjUsImV4cCI6MTY5ODc1MjcyNX0.SANd0C_3saBmzafLM74X6zHD0UsxG0yHrm31fnPGf3U
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
